name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download fonts
        run: |
          wget -q -O lmodern.zip "https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip"
          unzip -q -d fonts/ lmodern.zip

          wget -q -O iosevka.zip "https://github.com/be5invis/Iosevka/releases/download/v28.1.0/PkgTTC-Iosevka-28.1.0.zip"
          unzip -q -d fonts/ iosevka.zip

      - name: Typst
        # uses: lvignoli/typst-action@main
        # waiting for PR to be merged
        uses: leana8959/typst-action@main
        with:
          options: |
            --font-path
            fonts
          source_file: |
            main.typ

      # # Enable only when you need to print it
      # - name: Fix printer issues
      #   run: |
      #     apt-get update -y
      #     apt-get install ghostscript -y
      #     for f in *.pdf; do
      #       gs \
      #           -o "printable_$f" \
      #           -sDEVICE=pdfwrite \
      #           -dPDFSETTINGS=/prepress \
      #           "$f"
      #     done

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%Hh%M)" >> $GITHUB_ENV

      - name: Release
        uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          name: "${{ env.DATE }}"
          tag_name: "${{ env.DATE }}"
          files: |-
            *.pdf
