defaultTarget := 'main.typ'

compile:
	#!/usr/bin/env bash
	for f in *.typ; do
		typst compile "$f"
	done

compileAndFix: compile
	#!/usr/bin/env bash
	for f in *.pdf; do
		SRC="$f"
		DST="${f%.pdf}"_patched.pdf
		gs -o "$DST" \
			-sDEVICE=pdfwrite \
			-dPDFSETTINGS=/prepress \
			"$SRC"
		mv "$DST" "$SRC"
	done

sioyek target=defaultTarget: compile
	sioyek "{{ target }}" &
	typst watch "{{ target }}"

skim target=defaultTarget: compile
	open -a /Applications/Skim.app "{{ target }}"
	typst watch "{{ target }}"
