name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: docker
    container: leana8959/nix-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          nix build
          mkdir -p dist/release/
          mv ./result/*.pdf dist/release/

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%Hh%M)" >> $GITHUB_ENV

      - name: Release
        uses: https://git.earth2077.fr/leana/forgejo-release@fork
        with:
          direction: upload
          architecture: arm64
          tag: "${{ env.DATE }}"
